### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Raporaz03** [sanbabyfrancis/hacktoberfest-demo#20]
Update Readme By adding instruction to beginners, basic project ideas and add attracting images and gifs to make readme attractive.

**Comment by gustavomfb** [comment]
could you asign me this one?

**Comment by sanbabyfrancis** [comment]
@gustavomfb Sure, you may work on this issue. Thanks 😄 

@Jaizzer Hey, if you are interested in collaborating on this issue, please do let me know.

**Comment by Jaizzer** [comment]
Sure!
